export const skills = [
  "Amazon DynamoDB",
  "Android",
  "Angular",
  "Ansible",
  "Apache",
  "Apache Kafka",
  "ASP.NET",
  "AWS",
  "Azure",
  "Babel",
  "Bitbucket",
  "Bootstrap",
  "C",
  "C#",
  "C++",
  "Cassandra",
  "CircleCI",
  "CSS3",
  "Cypress",
  "Dart",
  "DigitalOcean",
  "Django",
  "Docker",
  "Express.js",
  "FastAPI",
  "Firebase Realtime Database",
  "Flask",
  "Flutter",
  "Git",
  "GitHub",
  "GitLab",
  "GitLab CI/CD",
  "Go",
  "Google Cloud Platform",
  "GraphQL",
  "gRPC",
  "Grunt",
  "Gulp",
  "Heroku",
  "HTML5",
  "IBM Cloud",
  "iOS",
  "Jasmine",
  "Java",
  "JavaScript",
  "Jenkins",
  "Jest",
  "JSON Web Tokens",
  "Keras",
  "Kotlin",
  "Kubernetes",
  "Laravel",
  "Microsoft Azure",
  "Microsoft IIS",
  "Microsoft SQL Server",
  "Mocha",
  "MongoDB",
  "MySQL",
  "Netlify",
  "Nginx",
  "Node.js",
  "npm",
  "OAuth",
  "OpenCV",
  "Oracle Database",
  "Penetration Testing tools (e.g., OWASP ZAP)",
  "PhoneGap/Cordova",
  "PHP",
  "PostgreSQL",
  "Python",
  "PyTorch",
  "Qt",
  "RabbitMQ",
  "React Native",
  "React.js",
  "Redis",
  "RESTful API",
  "Ruby",
  "Ruby on Rails",
  "Sass/SCSS",
  "Scikit-learn",
  "Security Headers",
  "Selenium",
  "Spring Boot",
  "SQLite",
  "SSL/TLS",
  "Swift",
  "TensorFlow",
  "Travis CI",
  "TypeScript",
  "Vercel",
  "Vue.js",
  "Webpack",
  "Xamarin",
  "Yarn",
];

export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "The Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo, Democratic Republic of the",
  "Congo, Republic of the",
  "Costa Rica",
  "Côte d’Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor (Timor-Leste)",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "The Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, North",
  "Korea, South",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia, Federated States of",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar (Burma)",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Sudan, South",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const designationCategories = [
  "Developer",
  "UX Designer",
  "Quality Assurance",
  "Project / Delivery Manager",
  "DevOps Specialist",
  "Solution Architect",
  "Business Analyst",
  "Security Specialist",
];
